server:
  port: 9000
  
spring:
  h2:
    console:
      enabled: true # 기본 값: false   
      path: /h2-console # 기본 값: h2-console
  datasource:
    generate-unique-name: false
    name: testdb # 기본 값 : testdb
    username: park # 기본 값 : sa
    password: 1234 # 기본 값 : (없음)
    